/**
 * Banned product terms — Sell Smart “YOU CAN’T SELL!” expanded list.
 * Matched against product name, description, variation, and condition.
 */

export const ILLEGAL_PRODUCT_MESSAGE =
  'This product is illegal and cannot be sold on Vibe Mart. See Sell Smart for the banned list.'

/** Category label → exact banned product phrases. */
export const ILLEGAL_PRODUCT_CATEGORIES = [
  {
    label: 'Weapons',
    terms: [
      'weapons',
      'weapon',
      'handgun',
      'pistol',
      'revolver',
      'rifle',
      'shotgun',
      'machine gun',
      'submachine gun',
      'assault rifle',
      'automatic firearm',
      'semi-automatic firearm',
      'firearm',
      'ghost gun',
      'sawed-off shotgun',
      'short-barreled rifle',
      'suppressor',
      'silencer',
      'ammunition',
      'bullets',
      'cartridges',
      'rifle ammunition',
      'pistol ammunition',
      'shotgun shells',
      'grenade',
      'land mine',
      'rocket launcher',
      'missile',
      'mortar',
      'bomb',
      'explosive',
      'detonator',
      'switchblade',
      'automatic knife',
      'brass knuckles',
      'knuckle duster',
      'stun gun',
      'taser',
      'electroshock weapon',
      'chemical weapon',
      'biological weapon',
      'incendiary weapon',
      'illegal fireworks',
      'professional fireworks',
      'explosive fireworks',
      'firecrackers',
      'large firecrackers',
      'homemade explosive',
      'improvised explosive',
      'explosive device',
      'bomb-making material',
      'detonating device',
      'blasting material',
      'blasting explosive',
      'military explosive',
      'military ammunition',
      'military weapon',
      'military firearm',
      'military equipment',
      'military night-vision equipment',
      'restricted military gear',
      'unauthorized body armor',
      'stolen body armor',
    ],
  },
  {
    label: 'Illegal drugs',
    terms: [
      'illegal drugs',
      'illegal drug',
      'heroin',
      'cocaine',
      'crack cocaine',
      'methamphetamine',
      'crystal meth',
      'mdma',
      'ecstasy',
      'lsd',
      'psilocybin',
      'magic mushrooms',
      'opium',
      'morphine',
      'illicit fentanyl',
      'carfentanil',
      'methadone',
      'ketamine',
      'pcp',
      'dmt',
      'mescaline',
      'crack',
      'meth',
      'ice',
      'molly',
      'acid',
      'shrooms',
      'hashish',
      'hash',
      'marijuana',
      'cannabis',
      'thc',
      'synthetic cannabis',
      'synthetic cannabinoids',
      'spice',
      'k2',
      'opium resin',
      'coca paste',
      'cocaine base',
      'illicit steroids',
      'black-market steroids',
      'drug paraphernalia',
    ],
  },
  {
    label: 'Tobacco or vaping products',
    terms: [
      'tobacco or vaping products',
      'tobacco products',
      'vaping products',
      'tobacco',
      'vaping',
      'vape',
      'cigarettes',
      'cigars',
      'cigarillos',
      'loose tobacco',
      'pipe tobacco',
      'chewing tobacco',
      'snuff',
      'snus',
      'nicotine pouches',
      'nicotine gum',
      'nicotine liquid',
      'e-liquid',
      'vape liquid',
      'vape juice',
      'disposable vape',
      'vape pen',
      'e-cigarette',
      'electronic cigarette',
      'vape cartridge',
      'nicotine cartridge',
    ],
  },
  {
    label: 'Alcohol',
    terms: [
      'alcohol',
      'alcoholic',
      'beer',
      'wine',
      'red wine',
      'white wine',
      'rose wine',
      'champagne',
      'sparkling wine',
      'vodka',
      'whiskey',
      'whisky',
      'bourbon',
      'scotch',
      'rum',
      'tequila',
      'gin',
      'brandy',
      'cognac',
      'liqueur',
      'liquor',
      'spirits',
      'absinthe',
      'moonshine',
      'hard cider',
      'alcoholic beverages',
      'distilled spirits',
    ],
  },
  {
    label: 'Prescription medicines',
    terms: [
      'prescription medicines',
      'prescription medicine',
      'prescription drugs',
      'prescription drug',
      'oxycodone',
      'hydrocodone',
      'codeine',
      'tramadol',
      'diazepam',
      'alprazolam',
      'lorazepam',
      'clonazepam',
      'methylphenidate',
      'amphetamine',
      'adderall',
      'ritalin',
      'fentanyl patches',
      'buprenorphine',
      'prescription opioids',
      'prescription stimulants',
      'prescription sedatives',
      'sleeping pills',
      'prescription benzodiazepines',
      'prescription painkillers',
      'prescription antibiotics',
      'prescription antidepressants',
      'prescription medication',
      'controlled medication',
      'controlled substances',
      'counterfeit branded medicine',
      'fake medicine',
      'fake prescription',
      'forged prescription',
      'counterfeit pharmaceutical',
      'unlicensed medicine',
      'unregistered medicine',
      'black-market medicine',
      'illicit medicine',
      'expired prescription medicine',
    ],
  },
  {
    label: 'Live animals',
    terms: [
      'live animals',
      'live animal',
      'live dog',
      'live cat',
      'live bird',
      'live parrot',
      'live eagle',
      'live falcon',
      'live owl',
      'live snake',
      'live python',
      'live cobra',
      'live turtle',
      'live tortoise',
      'live lizard',
      'live crocodile',
      'live alligator',
      'live monkey',
      'live ape',
      'live bat',
      'live fox',
      'live wolf',
      'live bear',
      'live tiger',
      'live lion',
      'live leopard',
      'live cheetah',
      'live elephant',
      'live rhino',
      'live giraffe',
      'live zebra',
      'live exotic animal',
      'protected wildlife',
      'endangered species',
      'exotic wildlife',
      'wild animal',
      'live primate',
      'live reptile',
      'live amphibian',
      'live insect',
      'live spider',
      'live scorpion',
      'live fish',
      'live shark',
      'live dolphin',
      'live whale',
      'live marine mammal',
      'illegal ivory',
      'elephant ivory',
      'rhino horn',
      'tiger parts',
      'lion parts',
      'protected animal skins',
      'protected animal bones',
      'protected animal teeth',
      'protected animal feathers',
      'endangered animal parts',
      'exotic animal skins',
      'illegal wildlife products',
      'protected coral',
      'cites-restricted wildlife',
    ],
  },
  {
    label: 'Counterfeit goods',
    terms: [
      'counterfeit goods',
      'counterfeit',
      'fake handbag',
      'fake purse',
      'fake designer bag',
      'counterfeit handbag',
      'counterfeit purse',
      'fake shoes',
      'fake sneakers',
      'fake designer shoes',
      'counterfeit shoes',
      'fake clothing',
      'fake designer clothing',
      'counterfeit clothing',
      'fake watch',
      'fake luxury watch',
      'counterfeit watch',
      'fake jewelry',
      'fake diamond',
      'fake gold',
      'counterfeit jewelry',
      'fake sunglasses',
      'fake perfume',
      'fake fragrance',
      'fake cosmetics',
      'counterfeit cosmetics',
      'fake makeup',
      'fake electronics',
      'counterfeit electronics',
      'fake smartphone',
      'fake phone',
      'fake tablet',
      'fake laptop',
      'fake headphones',
      'fake charger',
      'fake accessories',
      'fake branded product',
      'replica branded product',
      'counterfeit brand',
      'counterfeit merchandise',
      'counterfeit goods',
      'fake luxury goods',
      'fake trademarked product',
      'fake branded accessories',
      'fake sports jersey',
      'fake designer belt',
      'fake designer wallet',
      'fake passport',
      'counterfeit passport',
      'fake id card',
      'counterfeit id',
      'fake driver\'s license',
      'counterfeit driver\'s license',
      'fake visa',
      'counterfeit visa',
      'fake residence permit',
      'counterfeit certificate',
      'fake diploma',
      'fake degree',
      'forged document',
      'counterfeit document',
      'forged signature',
      'fake government document',
      'fake license',
      'counterfeit license',
      'fake banknote',
      'counterfeit banknote',
      'fake currency',
      'counterfeit currency',
      'forged money',
      'counterfeit coins',
      'fake checks',
      'counterfeit checks',
      'cloned credit card',
      'cloned debit card',
      'card skimmer',
      'payment card skimmer',
      'counterfeit bank card',
      'fake license plate',
      'counterfeit license plate',
      'counterfeit software',
      'pirated software',
      'cracked software',
      'pirated games',
      'pirated movies',
      'pirated music',
      'bootleg recordings',
      'unauthorized copies',
      'copyright-infringing copies',
      'pirated books',
      'unauthorized digital content',
      'fake software licenses',
      'unauthorized license keys',
      'pirated activation keys',
      'cracked license keys',
      'counterfeit gift cards',
      'fraudulent gift cards',
      'forged tickets',
      'counterfeit tickets',
      'fake event tickets',
      'counterfeit certificates',
    ],
  },
  {
    label: 'Stolen items',
    terms: [
      'stolen items',
      'stolen item',
      'stolen',
      'stolen phone',
      'stolen smartphone',
      'stolen laptop',
      'stolen computer',
      'stolen tablet',
      'stolen camera',
      'stolen television',
      'stolen electronics',
      'stolen headphones',
      'stolen jewelry',
      'stolen diamond',
      'stolen gold',
      'stolen watch',
      'stolen handbag',
      'stolen clothing',
      'stolen shoes',
      'stolen bicycle',
      'stolen motorcycle',
      'stolen car',
      'stolen truck',
      'stolen vehicle',
      'stolen automobile',
      'stolen artwork',
      'stolen painting',
      'stolen sculpture',
      'stolen antiques',
      'stolen collectibles',
      'stolen equipment',
      'stolen machinery',
      'stolen tools',
      'stolen property',
      'stolen goods',
      'stolen merchandise',
      'stolen goods for sale',
      'suspected stolen property',
      'stolen passport',
      'stolen id card',
      'stolen driver\'s license',
      'stolen license',
      'stolen credit card',
      'stolen debit card',
      'stolen bank card',
      'stolen financial information',
      'unauthorized payment card',
      'stolen vehicle parts',
      'stolen car parts',
      'stolen motorcycle parts',
      'stolen engine',
      'stolen vehicle engine',
      'stolen license plate',
      'stolen catalytic converter',
      'stolen car battery',
      'stolen fuel',
      'stolen construction equipment',
      'stolen agricultural equipment',
      'stolen industrial equipment',
      'stolen medical equipment',
      'stolen laboratory equipment',
      'stolen telecommunications equipment',
      'stolen network equipment',
      'stolen computer equipment',
      'stolen business equipment',
      'stolen access card',
      'cloned access card',
      'unauthorized keycard',
      'lock-picking tools',
      'bypass tools',
      'unauthorized master key',
      'stolen keys',
      'duplicate restricted keys',
      'counterfeit keys',
      'forged security credentials',
      'stolen gift cards',
      'stolen tickets',
      'stolen digital products',
      'stolen software licenses',
      'stolen archaeological artifacts',
      'illicit antiquities',
      'looted artifacts',
      'looted cultural property',
      'protected archaeological artifacts',
      'human organs',
      'human tissue',
      'human blood for unauthorized sale',
      'human remains',
      'human bones',
      'human skull',
      'restricted surveillance equipment',
      'illegal tracking device',
      'unauthorized tracking device',
      'hidden camera',
      'covert camera',
      'spy camera',
      'hidden microphone',
      'covert microphone',
      'spy microphone',
    ],
  },
  {
    label: 'Adult products',
    terms: [
      'adult products',
      'adult product',
      'sex toy',
      'adult toy',
      'sex doll',
      'love doll',
      'vibrator',
      'dildo',
      'anal toy',
      'masturbator',
      'sexual stimulator',
      'bdsm equipment',
      'bdsm restraints',
      'bondage equipment',
      'fetish equipment',
      'adult novelty',
      'adult merchandise',
      'sexual device',
      'erotic toy',
      'adult accessory',
      'sexual stimulant',
      'adult lubricant',
    ],
  },
  {
    label: 'Dangerous chemicals',
    terms: [
      'dangerous chemicals',
      'dangerous chemical',
      'cyanide',
      'hydrogen cyanide',
      'sodium cyanide',
      'potassium cyanide',
      'mercury',
      'arsenic',
      'arsenic trioxide',
      'lead compounds',
      'thallium',
      'beryllium compounds',
      'hydrofluoric acid',
      'sulfuric acid',
      'nitric acid',
      'hydrochloric acid',
      'perchloric acid',
      'phosphoric acid',
      'toxic pesticide',
      'restricted pesticide',
      'agricultural poison',
      'industrial poison',
      'chemical poison',
      'toxic chemical',
      'corrosive chemical',
      'radioactive material',
      'radioactive substance',
      'radioactive isotope',
      'uranium',
      'plutonium',
      'nuclear material',
      'chemical warfare agent',
      'nerve agent',
      'mustard agent',
      'toxic gas',
      'poison gas',
      'biological toxin',
      'ricin',
      'botulinum toxin',
      'sarin',
      'vx agent',
      'tabun',
      'soman',
      'explosive chemical',
      'restricted chemical',
      'hazardous chemical',
      'dangerous chemical',
    ],
  },
]

function normalizeText(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[’']/g, "'")
    .replace(/[^a-z0-9+\s-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function textMentionsTerm(haystack, term) {
  const needle = normalizeText(term)
  if (!needle || !haystack) return false
  if (needle.includes(' ')) return haystack.includes(needle)
  const pattern = new RegExp(`(?:^|[^a-z0-9])${escapeRegExp(needle)}(?:[^a-z0-9]|$)`, 'i')
  return pattern.test(haystack)
}

/**
 * Longer phrases first so “crack cocaine” wins over “crack”.
 * @param {{ name?: string, description?: string, variation?: string, condition?: string, label?: string }} product
 */
export function findIllegalProductMatch(product) {
  const haystack = normalizeText(
    [product?.name, product?.description, product?.variation, product?.condition, product?.label]
      .filter(Boolean)
      .join(' ')
  )
  if (!haystack) return { illegal: false }

  let best = null
  for (const category of ILLEGAL_PRODUCT_CATEGORIES) {
    for (const term of category.terms) {
      if (!textMentionsTerm(haystack, term)) continue
      if (!best || term.length > best.matchedTerm.length) {
        best = {
          illegal: true,
          category: category.label,
          matchedTerm: term,
          message: `This product is illegal (${category.label.toLowerCase()}) and cannot be sold on Vibe Mart.`,
        }
      }
    }
  }

  return best || { illegal: false }
}

export function isIllegalProduct(product) {
  return findIllegalProductMatch(product).illegal
}

/**
 * @param {Array} products
 * @returns {{ ok: boolean, errors: string[] }}
 */
export function validateProductsNotIllegal(products = []) {
  const errors = []
  ;(Array.isArray(products) ? products : []).forEach((product, index) => {
    const match = findIllegalProductMatch(product)
    if (!match.illegal) return
    const label = String(product?.name || `Product ${index + 1}`).trim() || `Product ${index + 1}`
    errors.push(`${label}: ${match.message || ILLEGAL_PRODUCT_MESSAGE}`)
  })
  return { ok: errors.length === 0, errors }
}
